name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.6'

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.julia/artifacts
        key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}-${{ hashFiles('**/Manifest.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-

    - name: Install dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests
      run: julia --project=@. -e 'using Pkg; Pkg.test()'
